version: '1.1.0.{build}'
configuration:
  - Debug
  - Release
build_script:
  - echo "Building for %CONFIGURATION%"
  - dotnet restore
  - dotnet build -c %CONFIGURATION%
test_script:
  - ps: dotnet test .\test\Pose.Tests\Pose.Tests.csproj
  - ps: if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
cache:
  - '%USERPROFILE%\.nuget\packages'
